services:
  descriptor-dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile

    volumes:
      # Mount your source code
      - .:/workspace
      # Mount X11 socket for GUI applications
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

    environment:
      # X11 forwarding for OpenCV display functions
      - DISPLAY=${DISPLAY}

    # Keep container running
    command: tail -f /dev/null

    stdin_open: true
    tty: true