experiment:
  name: "minimal_sift"
  description: "Minimal runnable config using SIFT"
  version: "1.0"
  author: "researcher"

dataset:
  type: "hpatches"
  path: "../data/"

keypoints:
  generator: "sift"
  max_features: 1000
  source: "homography_projection"

descriptors:
  - name: "sift"
    type: "sift"
    pooling: "none"
    normalize_after_pooling: true

evaluation:
  matching:
    method: "brute_force"
    norm: "l2"
    cross_check: true
    threshold: 0.8
  validation:
    method: "homography"
    threshold: 0.05
    min_matches: 10

output:
  results_path: "results/"
  save_keypoints: false
  save_descriptors: false
  save_matches: false
  save_visualizations: true

database:
  enabled: true
  connection: "sqlite:///experiments.db"

